version: "3"

services:
  app:
    image: golang:1.20
    ports:
      - 80:8000
    working_dir: /app
    volumes:
      - ./src:/app
    command: bash -c "cd /app && go run . -redis redis://redis:6379"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - ./data:/data
